[package]
name = "log_json_serializer"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { version = "0.4.29", features = ["kv_serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
